apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-argocd-certificate
spec:
  dnsNames:
  - argocd.grubis.cloud
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: letsencrypt-argocd-certificate