---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    solvers:
      - dns01:
          cloudflare:
            email: danigru@t-online.de
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token