apiVersion: v2
name: kubernetes-dashboard
description: A Helm chart for a kubernetes-dashboard

type: application

version: 0.0.1

dependencies:
  - name: kubernetes-dashboard
    version: 7.10.0
    repository: https://kubernetes.github.io/dashboard/