argo-cd:
  server:
    certificate:
      enabled: true
      domain: argocd.grubis.cloud
      issuer:
        group: cert-manager.io
        kind: ClusterIssuer
        name: letsencrypt

    ingress:
      enabled: true
      https: false
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: traefik
      hostname: argocd.grubis.cloud
      extraTls:
        - secretName: letsencrypt-argocd-certificate
          hosts:
            - argocd.grubis.cloud