argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: traefik
      hostname: argocd.grubis.cloud
      extraTls:
        - secretName: letsencrypt-argocd-certificate
          hosts:
            - argocd.grubis.cloud